version: '1.0'

services:
  productservice:
    image: souvikiiitb/speproject-productservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
      - apigatewayservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - logging.file.name=../logs/productservice/app.log    
    volumes:
      - ./Backend/logs/productservice:/app/logs/productservice
    networks:
      - springboot-mysql-network

  cartservice:
    image: souvikiiitb/speproject-cartservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8083:8083"
    depends_on:
      - productservice    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - productservice.url=http://productservice:8081/product-service
      - logging.file.name=../logs/cartservice/app.log      
    volumes:
      - ./Backend/logs/cartservice:/app/logs/cartservice
    networks:
      - springboot-mysql-network
  
  otpservice:
    image: souvikiiitb/speproject-otpservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8084:8084"
    depends_on:
      - mysqldb
      - apigatewayservice  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - logging.file.name=../logs/otpservice/app.log   
    volumes:
      - ./Backend/logs/otpservice:/app/logs/otpservice
    networks:
      - springboot-mysql-network

  loginservice:
    image: souvikiiitb/speproject-loginservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8085:8080"
    depends_on:
      - otpservice          
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - otpservice.url=http://otpservice:8084/otp-service
      - logging.file.name=../logs/loginservice/app.log      
    volumes:
      - ./Backend/logs/loginservice:/app/logs/loginservice
    networks:
      - springboot-mysql-network
  
  orderservice:
    image: souvikiiitb/speproject-orderservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8082:8082"
    depends_on:
      - productservice
      - cartservice      
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - productservice.url=http://productservice:8081/product-service
      - cartservice.url=http://cartservice:8083/cart-service
      - logging.file.name=../logs/orderservice/app.log      
    volumes:
      - ./Backend/logs/orderservice:/app/logs/orderservice
    networks:
      - springboot-mysql-network

  apigatewayservice:
    image: souvikiiitb/speproject-apigatewayservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8765:8765"
    depends_on:
      - eurekaserver      
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - logging.file.name=../logs/apigatewayservice/app.log      
    volumes:
      - ./Backend/logs/apigatewayservice:/app/logs/apigatewayservice
    networks:
      - springboot-mysql-network

  mysqldb:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=groceryapp
      - MYSQL_ROOT_PASSWORD=Pappu@1999      
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network

  eurekaserver:
    image: souvikiiitb/speproject-eurekaserver:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8761:8761"
    environment:      
      - logging.file.name=../logs/eurekaserver/app.log
    volumes:
      - ./Backend/logs/eurekaserver:/app/logs/eurekaserver
    networks:
      - springboot-mysql-network

  frontend:
    image: souvikiiitb/speproject-frontend:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "3000:3000"
    depends_on:
      - apigatewayservice
    networks:
      - springboot-mysql-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m          
    networks:
      - springboot-mysql-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.6
    volumes:
      - ./Backend/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - springboot-mysql-network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    ports:
      - "5601:5601"
    networks:
      - springboot-mysql-network
    depends_on:
      - elasticsearch
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.6
    volumes:
      - ./Backend/filebeat.yaml:/usr/share/filebeat/filebeat.yaml
      - ./Backend/logs:/usr/share/filebeat/logs
    networks:
      - springboot-mysql-network
    depends_on:
      - logstash
    
volumes:
  mysql-data:

networks:
  springboot-mysql-network:
    name: springboot-mysql-network