version: '1.0'

services:
  productservice:
    image: souvikiiitb/speproject-productservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
      - apigatewayservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    networks:
      - springboot-mysql-network

  cartservice:
    image: souvikiiitb/speproject-cartservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8083:8083"
    depends_on:
      - productservice    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
      - productservice.url=http://productservice:8081/product-service
    networks:
      - springboot-mysql-network
  
  otpservice:
    image: souvikiiitb/speproject-otpservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8084:8084"
    depends_on:
      - mysqldb
      - apigatewayservice  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    networks:
      - springboot-mysql-network

  loginservice:
    image: souvikiiitb/speproject-loginservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8085:8080"
    depends_on:
      - otpservice          
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - otpservice.url=http://otpservice:8084/otp-service
    networks:
      - springboot-mysql-network
  
  orderservice:
    image: souvikiiitb/speproject-orderservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8082:8082"
    depends_on:
      - productservice
      - cartservice      
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/groceryapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Pappu@1999
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - productservice.url=http://productservice:8081/product-service
      - cartservice.url=http://cartservice:8083/cart-service
    networks:
      - springboot-mysql-network

  apigatewayservice:
    image: souvikiiitb/speproject-apigatewayservice:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8765:8765"
    depends_on:
      - eurekaserver      
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/      
    networks:
      - springboot-mysql-network

  mysqldb:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=groceryapp
      - MYSQL_ROOT_PASSWORD=Pappu@1999      
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-mysql-network

  eurekaserver:
    image: souvikiiitb/speproject-eurekaserver:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "8761:8761"
    networks:
      - springboot-mysql-network

  frontend:
    image: souvikiiitb/speproject-frontend:latest  # Replace with your Docker Hub username and correct image name
    ports:
      - "3000:3000"
    depends_on:
      - apigatewayservice
    networks:
      - springboot-mysql-network

volumes:
  mysql-data:

networks:
  springboot-mysql-network:
    name: springboot-mysql-network